### ISSUE TITLE
wrong name of .toc-file

### ISSUE THREAD

**Issue by dired** [veechs/Postal-Returned#2]
Hello!

The toc-file has a space instead of a "-", which makes the addon not load.

When manually setting the "-", that leads to addon managers (from the new launcher or gitaddonmanager) resetting that change on update.

Cheers and thanks in advance

**Comment by veechs** [comment]
Thanks for the report! Just so we’re on the same page, the expectation ([as documented](https://github.com/veechs/Postal-Returned#installation)) is that the folder containing the addon will be given the same name as the TOC file, not the other way around. So
📄`Postal Returned.toc` ⇒ 📁`Postal Returned` (with a space).

The need to change the dash to a space is admittedly different from most other addons, where the only step for manual installation is to remove the branch name. But since I (and many others) have successfully used GitAddonsManager with the repository as-is, it never seemed to be a big problem.

I will test it with the Turtle launcher when I get a chance in case they’re doing something strange.

**Comment by veechs** [comment]
Finally got to do some testing with the Turtle WoW Launcher and you're right - it doesn't rename the addon folder to match the TOC like GitAddonsManager, so I added a new TOC file in fb6bc2361c2e947100bf62ff11e17f7603155462. This also led me to uncover a Launcher bug that I've [reported](https://turtle-wow.org/bug-report?id=10144) and worked around in c8e4bfd7135df61a2a545ca10e708dc610351953.

If you update to the latest version, I believe everything should work correctly with the TW Launcher. Thanks again for taking the time to report the issue!
